# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_entity_provider:
            entity:
                class:              AppBundle:User
                property:           username
    encoders:
        Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder:
            algorithm: bcrypt
            cost: 12            
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        crud:
            anonymous: ~
            form_login:
                default_target_path: /
                login_path: login
                check_path: login
                username_parameter: username
                password_parameter: password
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, roles: ROLE_ADMIN }        